experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train.tsv
    test_path: ../data/{0}/test.tsv
    side_information:
      - dataloader: VisualAttribute
        visual_features: ../data/{0}/image_feat
      - dataloader: TextualAttribute
        textual_features: ../data/{0}/text_feat
      - dataloader: AudioAttribute
        audio_features: ../data/{0}/audio_feat
  dataset: movielens
  top_k: 10
  evaluation:
    cutoffs: [10]
    simple_metrics: [ Recall, nDCG, EFD, Gini, APLT, ItemCoverage ]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:

    external.VBPR:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: True
        validation_rate: 10
        validation_metric: Recall@10
        restore: False
      lr: 0.001
      modalities: ('visual', 'textual')
      epochs: 30
      factors: [64, 128, 256, 384]
      batch_size: 1024
      l_w: [ 1e-5, 1e-2 ]
      comb_mod: concat
      seed: 42

    external.MMGCN:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: True
        validation_rate: 10
        validation_metric: Recall@10
        restore: False
      lr: 0.001 
      epochs: 30
      num_layers: [1, 2, 3]
      factors: [64, 128, 256, 384]
      factors_multimod: (128, None)
      batch_size: 1024
      aggregation: mean
      concatenation: False
      has_id: True
      modalities: ('visual', 'textual')
      l_w: [ 1e-5, 1e-2 ]
      seed: 42

    external.LATTICE:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: True
        validation_rate: 10
        validation_metric: Recall@10
        restore: False
      epochs: 30
      batch_size: 1024
      factors: [64, 128, 256, 384]
      factors_multimod: [64, 128, 256, 384]   # must match 'factors' parameter, so you need to run several times the script
      lr: 0.001
      l_w: [ 1e-5, 1e-2 ]
      n_layers: [1, 2, 3]
      n_ui_layers: 2
      top_k: 10
      l_m: 0.7
      modalities: ('visual', 'textual')
      seed: 42

    external.FREEDOM:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: True
        validation_rate: 10
        validation_metric: Recall@10
        restore: False
      lr: 0.001
      factors: [64, 128, 256, 384]
      factors_multimod: [64, 128, 256, 384]   # must match 'factors' parameter, so you need to run several times the script
      epochs: 30
      l_w: [1e-5, 1e-2]
      n_layers: [1, 2, 3]
      n_ui_layers: 2
      top_k: 10
      modalities: ('visual', 'textual')
      loaders: ('VisualAttribute','TextualAttribute')
      mw: (0.1,0.9)
      drop: 0.8
      lr_sched: (1.0,50)
      batch_size: 1024
      seed: 42