data_path: datasets/
LABEL_FIELD: label
benchmark_filename: ['train', 'valid', 'test']
dataset: 'dbbook'
checkpoint_dir: saved_dbbook/
model: 'KGIN'
epochs: 30
train_batch_size: 1024
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10000
seed: 42